FORMAT: 1A
HOST: http://invoicingForFreelancers.apiblueprint.org/

# InvoicingForFreelancers

Invicing for freelancers is a small app to handle invoicing in a small scale.

## Questions Collection [/questions]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "user": {
                    "first": "Natalie",
                    "last": "Mikesova",
                    "middle": "Marie"
                },
                "user_id": 1,
                "created_at": "2019-01-29T08:40:51.620Z",
                "settings": {
                    "licence": "active",
                }
            },
            {
                "user": {
                    "first": "Jindra",
                    "last": "Mikesova"
                },
                "user_id": 2,
                "created_at": "2019-01-29T08:40:51.620Z",
                "settings": {
                    "licence": "active",
                }
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "user": {
                "first": "Natalie",
                "last": "Mikesova",
                "middle": "Marie"
            },
            "user_id": 1,
            "created_at": "2019-01-29T08:40:51.620Z",
            "settings": {
                "licence": "active",
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/1

    + Body

            {
                "user": {
                    "first": "Natalie",
                    "last": "Mikesova",
                    "middle": "Marie"
                },
                "user_id": 1,
                "created_at": "2019-01-29T08:40:51.620Z",
                "settings": {
                    "licence": "active",
                }
            }